<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studenti [
<!ELEMENT studenti (student+)>
	<!ELEMENT student (mat_broj, ime, prezime, godina_studija)>
		<!ELEMENT mat_broj (#PCDATA)>
		<!ELEMENT ime (#PCDATA)>
		<!ELEMENT prezime (#PCDATA)>
		<!ELEMENT godina_studija (#PCDATA)>
	<!ATTLIST student tip CDATA #REQUIRED>
]>
<studenti>
	<student tip="redovni">
		<mat_broj>123</mat_broj>
		<ime>daniel</ime>
		<prezime>bele</prezime>
		<godina_studija>4</godina_studija>
	</student>	
	<student tip="izvanredni">
		<mat_broj>321</mat_broj>
		<ime>kolinda</ime>
		<prezime>grabar-kitaroviÄ‡</prezime>
		<godina_studija>1</godina_studija>
	</student>	
	<student tip="redovni">
		<mat_broj>312</mat_broj>
		<ime>vlatka</ime>
		<prezime>pokos</prezime>
		<godina_studija>5</godina_studija>
	</student>	
</studenti>
